"""Add category and image_url columns to Asset model

Revision ID: 2917cdf6df81
Revises: a9c2a322bebf
Create Date: 2024-07-29 18:40:22.675522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2917cdf6df81'
down_revision = 'a9c2a322bebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
