"""Add category column to Asset table

Revision ID: a9c2a322bebf
Revises: bcebc05aafaf
Create Date: 2024-07-29 18:06:39.882025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c2a322bebf'
down_revision = 'bcebc05aafaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
