"""deleted models

Revision ID: ec6e981cdb37
Revises: efaaa7ed870a
Create Date: 2024-08-07 16:23:33.467758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6e981cdb37'
down_revision = 'efaaa7ed870a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocated_to', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['allocated_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('allocated_to')

    # ### end Alembic commands ###
