"""deleted allocated to

Revision ID: efaaa7ed870a
Revises: 6fc5b4eee45f
Create Date: 2024-08-07 16:06:59.752666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efaaa7ed870a'
down_revision = '6fc5b4eee45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('assets_allocated_to_fkey', type_='foreignkey')
        batch_op.drop_column('allocated_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocated_to', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('assets_allocated_to_fkey', 'users', ['allocated_to'], ['id'])

    # ### end Alembic commands ###
