"""Add email column to user table

Revision ID: f1e34e5af8a6
Revises: 2917cdf6df81
Create Date: 2024-07-31 15:06:29.342728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e34e5af8a6'
down_revision = '2917cdf6df81'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))  # Set nullable=True initially
        batch_op.create_unique_constraint('uq_user_email', ['email'])  # Provide a name for the constraint
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
